agent_address = "/run/spire/sockets/agent.sock"
cert_dir = "/run/spiffe/certs"
daemon_mode = true
svid_file_name = "svid.pem"
svid_key_file_name = "svid_key.pem"
svid_bundle_file_name = "bundle.pem"
add_intermediates_to_bundle = true
cert_file_mode = 0644
key_file_mode = 0600
