apiVersion: v1
kind: Namespace
metadata:
  name: containgo
  labels:
    kubernetes.io/metadata.name: containgo
    containgo.io/spire-identity: "enabled"
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: containgo-workloads
spec:
  className: containgo
  spiffeIDTemplate: "spiffe://{{ .TrustDomain }}/ns/{{ .PodMeta.Namespace }}/sa/{{ .PodSpec.ServiceAccountName }}"
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: containgo
  podSelector:
    matchLabels:
      containgo.io/spiffe: "true"
  ttl: 30m
