apiVersion: v1
kind: Namespace
metadata:
  name: containgo
  labels:
    kubernetes.io/metadata.name: containgo
    containgo.io/spire-identity: enabled
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: protected-api
  namespace: containgo
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  namespace: containgo
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: control-plane
  namespace: containgo
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-client
  namespace: containgo
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: report-client
  namespace: containgo
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard
  namespace: containgo
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: democtl
  namespace: containgo
automountServiceAccountToken: false
