apiVersion: v1
kind: PersistentVolume
metadata:
  name: containgo-sqlite
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: containgo-hostpath
  hostPath:
    path: /var/lib/containgo
    type: Directory
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - containgo-control-plane
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: containgo-sqlite
  namespace: containgo
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: containgo-hostpath
  resources:
    requests:
      storage: 1Gi
  volumeName: containgo-sqlite
