apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace-serviceaccounts.yaml
  - 01-storage.yaml
  - 02-opa-policy.yaml
  - 10-protected-api.yaml
  - 11-control-plane.yaml
  - 12-api-gateway.yaml
  - 13-order-client.yaml
  - 14-report-client.yaml
  - 15-dashboard.yaml
  - 16-democtl.yaml
  - 20-network-policies.yaml
