package domain

import (
	"errors"
	"fmt"
	"time"
)

// StoredEvent represents a persisted security event together with every
// risk contribution calculated from it.
type StoredEvent struct {
	Event         SecurityEvent      `json:"event"`
	Contributions []RiskContribution `json:"contributions"`
	CreatedAt     time.Time          `json:"created_at"`
}

// Validate checks the persisted event and its contributions.
func (e StoredEvent) Validate() error {
	if e.Event.ID <= 0 {
		return errors.New(
			"stored event ID must be greater than zero",
		)
	}

	if err := e.Event.Validate(); err != nil {
		return fmt.Errorf(
			"validate security event: %w",
			err,
		)
	}

	if e.CreatedAt.IsZero() {
		return errors.New(
			"stored event created-at timestamp must not be zero",
		)
	}

	for index, contribution := range e.Contributions {
		if err := contribution.Validate(); err != nil {
			return fmt.Errorf(
				"validate contribution %d: %w",
				index,
				err,
			)
		}
	}

	return nil
}

// TotalContributionPoints returns the total number of points generated by
// this individual security event.
func (e StoredEvent) TotalContributionPoints() int {
	total := 0

	for _, contribution := range e.Contributions {
		total += contribution.Points
	}

	return total
}
